version: "3.8"

services:
  web:
    image: nginx:1.21.3
    container_name: auth-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      yandex:

  app:
    container_name: auth-app
    build:
      context: .
      target: prod
    expose:
      - "8008"
    depends_on:
      - redis
      - db
    volumes:
      - ./src/app:/code/app
      - ./src/manage.py:/code/manage.py
      - ./shared:/code/shared
      - ./shared/logs:/code/shared/logs
      - ./src/migrations:/code/migrations
    env_file:
      - .env
    networks:
      yandex:

  db:
    image: postgres:13
    container_name: auth-postgres
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      yandex:

  redis:
    image: redis:6.2.5
    container_name: auth-redis
    env_file:
      - .env
    expose:
      - "6379"
    command:
      - redis-server
    networks:
      yandex:

networks:
  yandex:
    external: true
  default:
